import type { CSSProperties } from "react";
import type { IconType } from "react-icons";
import {
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaArrowUp,
  FaAward,
  FaBars,
  FaBell,
  FaBrain,
  FaBug,
  FaBullhorn,
  FaCalendarDays,
  FaChartColumn,
  FaChartSimple,
  FaCheck,
  FaChevronDown,
  FaChevronRight,
  FaCircleCheck,
  FaCircleInfo,
  FaCircleQuestion,
  FaClock,
  FaCloud,
  FaCloudArrowUp,
  FaCode,
  FaCompassDrafting,
  FaCopy,
  FaDownload,
  FaEllipsis,
  FaEye,
  FaEnvelope,
  FaFilePdf,
  FaFileLines,
  FaGear,
  FaGraduationCap,
  FaHourglassHalf,
  FaIdBadge,
  FaListCheck,
  FaLock,
  FaMagnifyingGlass,
  FaMoon,
  FaPenRuler,
  FaQrcode,
  FaRightFromBracket,
  FaShareNodes,
  FaShieldHalved,
  FaSun,
  FaTableCellsLarge,
  FaTerminal,
  FaTriangleExclamation,
  FaTrophy,
  FaUpload,
  FaUser,
  FaUsers,
  FaUserShield,
  FaWallet,
} from "react-icons/fa6";
import { HiBuildingLibrary, HiOutlineBuildingOffice2 } from "react-icons/hi2";

type MaterialIconProps = {
  children: string;
  filled?: boolean;
  className?: string;
  style?: CSSProperties;
};

const iconMap: Record<string, IconType> = {
  account_balance: HiBuildingLibrary,
  architecture: FaCompassDrafting,
  arrow_back: FaArrowLeft,
  arrow_downward: FaArrowDown,
  arrow_forward: FaArrowRight,
  arrow_upward: FaArrowUp,
  bug_report: FaBug,
  calendar_month: FaCalendarDays,
  campaign: FaBullhorn,
  badge: FaIdBadge,
  check: FaCheck,
  check_circle: FaCircleCheck,
  check_circle_outline: FaCircleCheck,
  checklist: FaListCheck,
  chevron_right: FaChevronRight,
  cloud_done: FaCloudArrowUp,
  cloud_sync: FaCloud,
  code: FaCode,
  content_copy: FaCopy,
  dashboard: FaTableCellsLarge,
  design_services: FaPenRuler,
  description: FaFileLines,
  domain: HiOutlineBuildingOffice2,
  download: FaDownload,
  error_outline: FaTriangleExclamation,
  event: FaCalendarDays,
  expand_more: FaChevronDown,
  groups: FaUsers,
  help: FaCircleQuestion,
  hourglass_empty: FaHourglassHalf,
  info: FaCircleInfo,
  insights: FaChartColumn,
  light_mode: FaSun,
  lock: FaLock,
  logout: FaRightFromBracket,
  mail: FaEnvelope,
  menu: FaBars,
  military_tech: FaTrophy,
  monitoring: FaChartSimple,
  more_horiz: FaEllipsis,
  notifications: FaBell,
  payments: FaWallet,
  person: FaUser,
  picture_as_pdf: FaFilePdf,
  psychology: FaBrain,
  qr_code_2: FaQrcode,
  school: FaGraduationCap,
  schedule: FaClock,
  search: FaMagnifyingGlass,
  security: FaUserShield,
  settings: FaGear,
  share: FaShareNodes,
  task: FaListCheck,
  terminal: FaTerminal,
  upload: FaUpload,
  upload_file: FaUpload,
  verified: FaShieldHalved,
  verified_user: FaUserShield,
  visibility: FaEye,
  workspace_premium: FaAward,
  dark_mode: FaMoon,
};

export function MaterialIcon({
  children,
  className,
  style,
}: MaterialIconProps) {
  const Icon = iconMap[children] ?? FaCircleQuestion;

  return (
    <Icon
      aria-hidden="true"
      style={style}
      className={["fp-icon", className ?? ""].filter(Boolean).join(" ")}
    />
  );
}
