import type { CSSProperties } from "react";
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Award,
  Menu,
  Bell,
  Brain,
  Bug,
  Megaphone,
  CalendarDays,
  BarChart2,
  LineChart,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  CheckCircle2,
  Info,
  HelpCircle,
  Clock,
  Cloud,
  CloudUpload,
  Code,
  PenTool,
  Copy,
  Download,
  MoreHorizontal,
  Eye,
  Mail,
  FileText,
  FileIcon,
  Settings,
  GraduationCap,
  Hourglass,
  Badge,
  ListChecks,
  Lock,
  Search,
  Moon,
  QrCode,
  LogOut,
  Share2,
  ShieldCheck,
  Sun,
  LayoutDashboard,
  Terminal,
  AlertTriangle,
  Medal,
  Upload,
  FileUp,
  User,
  Users,
  Wallet,
  Building2,
  Building,
  ListTodo,
  X,
  Trash2,
  Filter,
  History,
  RefreshCw,
  PieChart,
  Palette,
  Tags,
  ScanQrCode,
  Shield,
  Edit2,
  Compass,
  UserCircle2,
  Headset,
  LifeBuoy,
  Plus,
} from "lucide-react";

type MaterialIconProps = {
  children: string;
  filled?: boolean;
  className?: string;
  style?: CSSProperties;
};

const iconMap: Record<string, React.ElementType> = {
  account_balance: Building2,
  architecture: PenTool,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  bug_report: Bug,
  calendar_month: CalendarDays,
  campaign: Megaphone,
  category: Tags,
  badge: Badge,
  check: Check,
  check_circle: CheckCircle2,
  check_circle_outline: CheckCircle2,
  checklist: ListChecks,
  chevron_right: ChevronRight,
  close: X,
  cloud_done: CloudUpload,
  cloud_sync: Cloud,
  cloud: Cloud,
  account_circle: UserCircle2,
  contact_support: Headset,
  code: Code,
  color_lens: Palette,
  content_copy: Copy,
  dashboard: LayoutDashboard,
  delete: Trash2,
  design_services: PenTool,
  description: FileText,
  domain: Building,
  download: Download,
  error_outline: AlertTriangle,
  event: CalendarDays,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  filter_list: Filter,
  groups: Users,
  help: LifeBuoy,
  help_center: LifeBuoy,
  list_alt: ListChecks,
  history: History,
  hourglass_empty: Hourglass,
  info: Info,
  insights: BarChart2,
  light_mode: Sun,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  menu: Menu,
  military_tech: Medal,
  monitoring: LineChart,
  more_horiz: MoreHorizontal,
  notifications: Bell,
  palette: Palette,
  payments: Wallet,
  person: User,
  picture_as_pdf: FileIcon,
  pie_chart: PieChart,
  psychology: Brain,
  qr_code_2: QrCode,
  qr_code_scanner: ScanQrCode,
  refresh: RefreshCw,
  school: GraduationCap,
  schedule: Clock,
  search: Search,
  security: ShieldCheck,
  settings: Settings,
  share: Share2,
  shield: Shield,
  task: ListTodo,
  terminal: Terminal,
  upload: Upload,
  upload_file: FileUp,
  verified: ShieldCheck,
  verified_user: ShieldCheck,
  visibility: Eye,
  warning: AlertTriangle,
  workspace_premium: Award,
  dark_mode: Moon,
  add: Plus,
  edit: Edit2,
  email: Mail,
  interests: Compass,
};

export function MaterialIcon({
  children,
  className,
  style,
}: MaterialIconProps) {
  const Icon = iconMap[children] ?? HelpCircle;

  return (
    <Icon
      aria-hidden="true"
      style={style}
      className={["fp-icon", className ?? ""].filter(Boolean).join(" ")}
    />
  );
}
